### ISSUE TITLE
Not rendering Character Cards at all (not getting into map of Display Container 2nd time around)

### ISSUE THREAD

**Issue by hfaerber** [ckoga/SWAPI-Study-Sesh#12]
On click of the `View Characters` button:
- Successfully fires fetchChar() (console.logs('get em')
- Successfully routes to <Link> path /movies/:movie_id
- Successfully renders the `<Route path='/movies/:movie_id' ` option in App.js
- Successfully gets into `Display Container` with `isMovies` prop as 'undefined' (falsey)
- Successfully console.logs on line 8
- Never gets to the console.log on line 10

I can't figure out why it isn't getting into the map function the second time around and rendering the ELSE block like we want it to.

**Comment by ckoga** [comment]
I made a comment in PR #13, but the main issue is we don't have any characters in our ```this.state.characters``` array.  I added a simple object in and ran everything again and was able to get our character card to display.  I am going to merge 13 and close out this issue.

**Comment by hfaerber** [comment]
Thank you for figuring this out Colin!  Such a silly oversight on my part.  I really appreciate you taking the time to walk through it and figure out what the issue was.
